{% set name = "warpx" %}
{% set version = "21.05" %}
{% set build = 0 %}
{% set sha256 = "f835f0ae6c5702550d23191aa0bb0722f981abb1460410e3d8952bc3d945a9fc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ECP-WarpX/WarpX/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  run_exports:
    # releases are not (yet) compatible
    - warpx {{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ccache
    - clang         # [win]
    - lld           # [win]
    - make          # [unix]
    - ninja         # [win]
    - cmake >=3.15.0
    - libgomp       # [linux]
    - llvm-openmp   # [osx or win]
  host:
    - blaspp
    - boost-cpp
    - lapackpp
    - openpmd-api
    - pip
    - python
    - setuptools
    - wheel
    - fftw
    - pkgconfig
# ninja: error: 'D:/bld/warpx_1615224319242/_h_env/Library/lib/lapack.lib', needed by 'lib/warpx.RZ.NOMPI.OMP.DP.OPMD.PSATD.QED.dll', missing and no known rule to make it
    - liblapack   # [win]
    - liblapacke  # [win]
  run:
    - numpy
    - periodictable
    - picmistandard ==0.0.14
    - python
    - scipy

test:
  imports:
    - pywarpx
  commands:
    - test -f ${PREFIX}/bin/warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED  # [unix]
    - test -f ${PREFIX}/bin/warpx.3d.NOMPI.OMP.DP.OPMD.PSATD.QED  # [unix]
    - test -f ${PREFIX}/bin/warpx.RZ.NOMPI.OMP.DP.OPMD.PSATD.QED  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\warpx.2d.NOMPI.OMP.DP.OPMD.PSATD.QED.exe (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\bin\warpx.3d.NOMPI.OMP.DP.OPMD.PSATD.QED.exe (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\bin\warpx.RZ.NOMPI.OMP.DP.OPMD.PSATD.QED.exe (exit 0) else (exit 1)  # [win]

about:
  home: https://ecp-warpx.github.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: WarpX is an advanced electromagnetic Particle-In-Cell code.

  description: |
    WarpX is an advanced electromagnetic Particle-In-Cell code.
    It supports many features including: Perfectly-Matched Layers (PML),
    Boosted-frame simulations, particle collisions, mesh refinement.

  doc_url: https://warpx.readthedocs.io
  dev_url: https://github.com/ECP-WarpX/WarpX

extra:
  recipe-maintainers:
    - ax3l
    - RemiLehe
