{% set name = "warpx" %}
{% set version = "20.12" %}
{% set build = 0 %}
{% set sha256 = "f241fecd9c5a324efb2c83d4a4b810f0bbb268dfa53b9b6bd2a5e18acc0d7ff4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ECP-WarpX/WarpX/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  run_exports:
    # releases are not (yet) compatible
    - warpx {{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ccache
    - clang         # [win]
    - make          # [unix]
    - ninja         # [win]
    - cmake >=3.14.0
    - libgomp       # [linux]
    - llvm-openmp   # [osx or win]
  host:
    - boost-cpp
    - openmpi                      # [unix]
    - openpmd-api * mpi_openmpi_*  # [unix]
    - openpmd-api                  # [win]
# future
#    - fftw * mpi_openmpi_*         # [unix]
#    - fftw                         # [win]
# a variant could provide CUDA support

test:
  commands:
    - test -f ${PREFIX}/bin/warpx.2d.MPI.OMP.DP.OPMD.QED  # [unix]
    - test -f ${PREFIX}/bin/warpx.3d.MPI.OMP.DP.OPMD.QED  # [unix]
    - test -f ${PREFIX}/bin/warpx.RZ.MPI.OMP.DP.OPMD.QED  # [unix]

about:
  home: https://ecp-warpx.github.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: WarpX is an advanced electromagnetic Particle-In-Cell code.

  description: |
    WarpX is an advanced electromagnetic Particle-In-Cell code.
    It supports many features including: Perfectly-Matched Layers (PML),
    Boosted-frame simulations, particle collisions, mesh refinement.

  doc_url: https://warpx.readthedocs.io
  dev_url: https://github.com/ECP-WarpX/WarpX

extra:
  recipe-maintainers:
    - ax3l
    - RemiLehe
