build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  # have to migrate blaspp and lapackpp first
  # osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  # Travis 50min timeout is too short
  linux_ppc64le: azure
  win: azure
test_on_native_only: true
